export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const ON_PURCHASE = 'ON_PURCHASE'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'

export const FETCH_ORDER = 'FETCH_ORDER'
export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT"